name: SSH Deploy or Command

on:
  push:
    branches: [test]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from mcp-pack'
        required: true
        default: 'main'
        type: string
jobs:
  remote-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Redeploy with ssh
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} bash -c "'
            echo Hello from Starsim
            cd /home/starsim/mcp-pack
            git fetch
            git checkout ${{ github.event.inputs.branch || 'main' }}
            git pull
            kill -9 $(lsof -ti :8001)
            kill -9 $(lsof -ti :8002)
            sleep 3
            nohup uv run python -m mcp_pack.server --module_name=sciris --port=8001 --transport=sse > sciris.log 2>&1 &
            nohup uv run python -m mcp_pack.server --module_name=starsim --port=8002 --transport=sse > starsim.log 2>&1 &
            echo '--- sciris server logs ---'
            cat sciris.log
            echo '--- starsim server logs ---'
            cat starsim.log
            echo 'Deployment complete'
          '"

      - name: Check if both ports are running
        run: |
          for port in 8001 8002; do
            if ! ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} lsof -ti :$port; then
              echo "Port $port is not in use. Please investigate the deployment."
              exit 1
            else
              echo "Port $port is in use."
            fi
          done
        shell: bash
